### ISSUE TITLE
Wrong CSS rule in Air.css

### ISSUE THREAD

**Issue by Studio384** [GetLuna/Luna#13]
I just found this rule in Air.css:

``` css
.pun .linkst .inbox, .pun linksb .inbox, .pun .postlinksb .inbox {
    overflow: hidden;
}
```

Obviously, "linksb" should be a class name in the second selector.

Not sure whether we have this error in other stylesheets, too.
